#!/usr/bin/env python3
"""Generate entities.rs from the local Python stdlib (html.entities.html5).

Usage: python3 html2text_rs/gen_entities.py > html2text_rs/src/entities.rs
"""

import html.entities

UNIFIABLE = {
    "rsquo": "'",
    "lsquo": "'",
    "rdquo": '"',
    "ldquo": '"',
    "copy": "(C)",
    "mdash": "--",
    "nbsp": " ",
    "rarr": "->",
    "larr": "<-",
    "middot": "*",
    "ndash": "-",
    "oelig": "oe",
    "aelig": "ae",
    "agrave": "a",
    "aacute": "a",
    "acirc": "a",
    "atilde": "a",
    "auml": "a",
    "aring": "a",
    "egrave": "e",
    "eacute": "e",
    "ecirc": "e",
    "euml": "e",
    "igrave": "i",
    "iacute": "i",
    "icirc": "i",
    "iuml": "i",
    "ograve": "o",
    "oacute": "o",
    "ocirc": "o",
    "otilde": "o",
    "ouml": "o",
    "ugrave": "u",
    "uacute": "u",
    "ucirc": "u",
    "uuml": "u",
    "lrm": "",
    "rlm": "",
}


def esc(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if o == 0x27:
            out.append("\\'")
        elif o == 0x5C:
            out.append("\\\\")
        elif o == 0x22:
            out.append('\\"')
        elif o == 0x0A:
            out.append("\\n")
        elif 0x20 <= o < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{{{o:x}}}")
    return "".join(out)


lines = []
lines.append("// @generated by gen_entities.py — do not edit by hand.")
lines.append("// Mirrors the local Python stdlib html.entities.html5 table.")
lines.append("//")
lines.append("// Static table built at compile time (phf). No HashMap rebuild at")
lines.append("// runtime, single O(1) lookup, no SipHash. Keys are emitted in")
lines.append("// sorted order for deterministic builds.")
lines.append("use phf::phf_map;")
lines.append("")
lines.append("pub static HTML5_ENTITIES: phf::Map<&'static str, &'static str> = phf_map! {")
for name, val in sorted(html.entities.html5.items()):
    lines.append('    "%s" => "%s",' % (esc(name), esc(val)))
lines.append("};")
lines.append("")
lines.append("pub const UNIFIABLE: &[(&str, &str)] = &[")
for k, v in sorted(UNIFIABLE.items()):
    lines.append('    ("%s", "%s"),' % (esc(k), esc(v)))
lines.append("];")
lines.append("")
lines.append("pub const UNIFIABLE_N: &[(u32, &str)] = &[")
for k, v in sorted(UNIFIABLE.items()):
    if k == "nbsp":
        continue
    cp = html.entities.name2codepoint[k]
    lines.append('    (0x%X, "%s"),' % (cp, esc(v)))
lines.append("];")
print("\n".join(lines))
